Traceback (most recent call last):
  File "/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/main.py", line 27, in <module>
    main()
  File "/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/main.py", line 23, in main
    args.func(args)
  File "/cobra/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/cli.py", line 141, in train_func
    train_single_cnn(args)
  File "/cobra/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/train/train_singleCNN.py", line 114, in train_single_cnn
    optimizer, False, log_dir, model_dir, params, train_logger)
  File "/cobra/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/tools/deep_learning/cnn_utils.py", line 104, in train
    train_output = model(imgs)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cobra/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/tools/deep_learning/models/modules.py", line 407, in forward
    x = self.layer2(x)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cobra/u/horlavanasta/MasterProject/Code/ClinicaTools/AD-DL/clinicaaddl/clinicaaddl/tools/deep_learning/models/modules.py", line 323, in forward
    out = self.bn3(out)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/mpcdf/soft/SLE_12/packages/skylake/pytorch/gpu/anaconda_3_2020.02-2020.02-cuda_10.2-10.2.89/1.6.0/lib/python3.7/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 386.00 MiB (GPU 0; 31.75 GiB total capacity; 29.91 GiB already allocated; 319.50 MiB free; 30.27 GiB reserved in total by PyTorch)
srun: error: co6027: task 0: Exited with exit code 1
srun: Terminating job step 3953403.0
